source 'https://rubygems.org'
gem 'rack'
gem 'bootstrap-sass'
gem 'compass'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'nokogiri'
gem 'elasticsearch', git: 'git://github.com/elasticsearch/elasticsearch-ruby.git'
gem 'jbuilder'
gem 'hashie'
gem 'pry-nav'
gem 'pry'
gem 'thin'
